export default interface SymbolIcon {
  arrayForeground: string
  booleanForeground: string
  classForeground: string
  colorForeground: string
  constantForeground: string
  constructorForeground: string
  enumeratorForeground: string
  enumeratorMemberForeground: string
  eventForeground: string
  fieldForeground: string
  fileForeground: string
  folderForeground: string
  functionForeground: string
  interfaceForeground: string
  keyForeground: string
  keywordForeground: string
  methodForeground: string
  moduleForeground: string
  namespaceForeground: string
  nullForeground: string
  numberForeground: string
  objectForeground: string
  operatorForeground: string
  packageForeground: string
  propertyForeground: string
  referenceForeground: string
  snippetForeground: string
  stringForeground: string
  structForeground: string
  textForeground: string
  typeParameterForeground: string
  unitForeground: string
  variableForeground: string
}
