import { removeNullStrAttr } from '../utils/index.js'

export default async function createThemeColors() {
  const _colors = {
    ...(await import('./action-colors.js')).default,
    ...(await import('./activity-bar.js')).default,
    ...(await import('./badge.js')).default,
    ...(await import('./banner-colors.js')).default,
    ...(await import('./breadcrumbs-colors.js')).default,
    ...(await import('./base-colors.js')).default,
    ...(await import('./button-control.js')).default,
    ...(await import('./chart-colors.js')).default,
    ...(await import('./command-center-colors.js')).default,
    ...(await import('./constrast-colors.js')).default,
    ...(await import('./debug.js')).default,
    ...(await import('./diff-editor-colors.js')).default,
    ...(await import('./dropdown-control.js')).default,
    ...(await import('./editor.js')).default,
    ...(await import('./extensions-colors.js')).default,
    ...(await import('./git-colors.js')).default,
    ...(await import('./input-control.js')).default,
    ...(await import('./keybinding.js')).default,
    ...(await import('./lists.js')).default,
    ...(await import('./menu.js')).default,
    ...(await import('./merge-conflicts-colors.js')).default,
    ...(await import('./minimap.js')).default,
    ...(await import('./notebook-colors.js')).default,
    ...(await import('./notification-colors.js')).default,
    ...(await import('./panel-colors.js')).default,
    ...(await import('./peek-view-colors.js')).default,
    ...(await import('./picker-group.js')).default,
    ...(await import('./ports-colors.js')).default,
    ...(await import('./progress-bar.js')).default,
    ...(await import('./quick-input.js')).default,
    ...(await import('./quick-picker-colors.js')).default,
    ...(await import('./scrollbar-control.js')).default,
    ...(await import('./selection.js')).default,
    ...(await import('./settings.js')).default,
    ...(await import('./side-bar.js')).default,
    ...(await import('./snippets-colors.js')).default,
    ...(await import('./source-control-color.js')).default,
    ...(await import('./status-bar-colors.js')).default,
    ...(await import('./symbol-icons-colors.js')).default,
    ...(await import('./tab.js')).default,
    ...(await import('./terminal.js')).default,
    ...(await import('./testing-color.js')).default,
    ...(await import('./tree.js')).default,
    ...(await import('./welcome-page-colors.js')).default,
    ...(await import('./widget.js')).default,
    ...(await import('./window.js')).default
  }

  return removeNullStrAttr(_colors)
}
