import colors from '../../designs/index.js'

const tsxOperator = {
  name: 'tsx::operator',
  scope: [
    'keyword.operator.assignment.tsx',
    'keyword.operator.comparison.tsx',
    'keyword.operator.logical.tsx',
    'keyword.operator.arithmetic.tsx',
    'keyword.operator.expression.typeof.tsx',
    'keyword.operator.expression.instanceof.tsx',
    'keyword.operator.increment.tsx',
    'keyword.operator.decrement.tsx',
    'keyword.operator.relational.tsx',
    'keyword.operator.expression.delete.tsx',
    'keyword.operator.new.tsx',
    'keyword.operator.bitwise.tsx',
    'keyword.operator.bitwise.shift.tsx',
    'keyword.operator.spread.tsx',
    'keyword.operator.ternary.tsx',
    'keyword.operator.assignment.compound.tsx',
    'keyword.operator.assignment.compound.bitwise.tsx',
    'keyword.operator.expression.in.tsx',
    'keyword.operator.expression.void.tsx',
    'punctuation.accessor.optional.tsx',
    'punctuation.separator.comma.tsx',
    'keyword.generator.asterisk.tsx',
    'keyword.control.as.tsx',
    'keyword.control.switch.tsx',
    'keyword.control.switch.tsx',
    'storage.type.property.tsx',
    'keyword.operator.optional.tsx',
    'keyword.operator.type.annotation.tsx',
    'keyword.operator.type.tsx',
    'keyword.control.trycatch.tsx',
    // jsx
    'keyword.operator.assignment.jsx',
    'keyword.operator.comparison.jsx',
    'keyword.operator.logical.jsx',
    'keyword.operator.arithmetic.jsx',
    'keyword.operator.expression.typeof.jsx',
    'keyword.operator.expression.instanceof.jsx',
    'keyword.operator.increment.jsx',
    'keyword.operator.decrement.jsx',
    'keyword.operator.relational.jsx',
    'keyword.operator.expression.delete.jsx',
    'keyword.operator.new.jsx',
    'keyword.operator.bitwise.jsx',
    'keyword.operator.bitwise.shift.jsx',
    'keyword.operator.spread.jsx',
    'keyword.operator.ternary.jsx',
    'keyword.operator.assignment.compound.jsx',
    'keyword.operator.assignment.compound.bitwise.jsx',
    'keyword.operator.expression.in.jsx',
    'keyword.operator.expression.void.jsx',
    'punctuation.accessor.optional.jsx',
    'punctuation.separator.comma.jsx',
    'keyword.generator.asterisk.jsx',
    'keyword.control.as.jsx',
    'keyword.control.switch.jsx',
    'keyword.control.switch.jsx',
    'storage.type.property.jsx',
    'keyword.operator.optional.jsx',
    'keyword.operator.type.annotation.jsx',
    'keyword.operator.type.jsx',
    'keyword.control.trycatch.jsx'
  ],
  settings: {
    foreground: colors.magentaColors600,
    fontStyle: 'bold'
  }
}

export default [tsxOperator]
